# -*- coding: utf-8 -*-
"""oddEven.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBeAFBaiQvja0B0tTG8M3D0Ob8TCF_ci
"""

num = int(input("Enter the number = "))
if num%2 == 0 :
    print("The number is even")
else :
    print("The number is odd")