# -*- coding: utf-8 -*-
"""sum1to50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBeAFBaiQvja0B0tTG8M3D0Ob8TCF_ci
"""

sum = 0
for i in range (1,51):
  sum = sum + i
print (f"Sum of number from 1 to 50 is : {sum}")